# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# compile CXX with /usr/bin/c++
CXX_FLAGS =  -Wno-invalid-offsetof  -Wno-deprecated -I/usr/include/vtk -I/usr/include/pcl-1.6 -I/usr/include/eigen3 -I/usr/include/qhull -I/home/s1143956/Analysis/LSDTopoTools/trunk/driver_functions_DTM_devel/SwathProfiles/build_river_swath/../.. -I/home/s1143956/Analysis/LSDTopoTools/trunk/driver_functions_DTM_devel/SwathProfiles/build_river_swath/../../../TNT    -DDISABLE_LIBUSB-1.0

CXX_DEFINES = -DDISABLE_OPENNI -DEIGEN_USE_NEW_STDVECTOR -DEIGEN_YES_I_KNOW_SPARSE_MODULE_IS_NOT_STABLE_YET -Dqh_QHpointer

