name: docs
on:
  push:
    paths:
      - docs/**
    branches:
      - main
  pull_request:
  schedule:
    - cron: 0 0 1 * * # run workflow at 12AM on first day of every month
  workflow_dispatch:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
      - name: Install dependencies, and Sphinx then build docs
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinxcontrib-fulltoc
          (cd docs && make html)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
